INSERT INTO
	Pais (Codigo, Descricao)
VALUES
	('BRA', 'Brasil'),
	('AFG', 'Afeganistão'),
	('ZAF', 'África do Sul'),
	('ALB', 'Albânia'),
	('DEU', 'Alemanha'),
	('AND', 'Andorra'),
	('AGO', 'Angola'),
	('AIA', 'Anguilla'),
	('ATA', 'Antárctida'),
	('ATG', 'Antígua e Barbuda'),
	('ANT', 'Antilhas Holandesas'),
	('SAU', 'Arábia Saudita'),
	('DZA', 'Argélia'),
	('ARG', 'Argentina'),
	('ARM', 'Arménia'),
	('ABW', 'Aruba'),
	('AUS', 'Austrália'),
	('AUT', 'Austria'),
	('AZE', 'Azerbaijão'),
	('BHS', 'Bahamas'),
	('BHR', 'Bahrein'),
	('BGD', 'Bangladesh'),
	('BRB', 'Barbados'),
	('BEL', 'Bélgica'),
	('BLZ', 'Belize'),
	('BEN', 'Benim'),
	('BMU', 'Bermudas'),
	('BLR', 'Bielorrússia'),
	('BTN', 'Butão'),
	('BOL', 'Bolívia'),
	('BIH', 'Bósnia e Herzegovina'),
	('BWA', 'Botsuana'),
	('BRN', 'Brunei'),
	('BGR', 'Bulgária'),
	('BFA', 'Burkina Faso'),
	('BDI', 'Burundi'),
	('KHM', 'Camboja'),
	('CMR', 'Camarões'),
	('CAN', 'Canadá'),
	('CPV', 'Cabo Verde'),
	('CYM', 'Ilhas Cayman'),
	('KAZ', 'Cazaquistão'),
	('TCD', 'Chade'),
	('CHL', 'Chile'),
	('CHN', 'China'),
	('CYP', 'Chipre'),
	('CXR', 'Ilha Christmas'),
	('COL', 'Colômbia'),
	('COM', 'Comores'),
	('COG', 'Congo'),
	('COK', 'Ilhas Cook'),
	('PPK', 'Coreia do Norte'),
	('KOR', 'Coreia do Sul'),
	('CRI', 'Costa Rica'),
	('CIV', 'Costa do Marfim'),
	('HRV', 'Croácia'),
	('CUB', 'Cuba'),
	('DNK', 'Dinamarca'),
	('DJI', 'Djibouti'),
	('DMA', 'Dominica'),
	('ECU', 'Equador'),
	('EGY', 'Egito'),
	('SLV', 'El Salvador'),
	('ARE', 'Emirados Árabes Unidos'),
	('ERI', 'Eritreia'),
	('SCO', 'Escócia'),
	('SVK', 'Eslováquia'),
	('ESP', 'Espanha'),
	('USA', 'Estados Unidos'),
	('EST', 'Estônia'),
	('ETH', 'Etiópia'),
	('FRO', 'Ilhas Feroé'),
	('FJI', 'Fiji'),
	('PHL', 'Filipinas'),
	('FIN', 'Finlândia'),
	('FRA', 'França'),
	('GAB', 'Gabão'),
	('GHA', 'Gana'),
	('GMB', 'Gâmbia'),
	('GEO', 'Geórgia'),
	('GIB', 'Gibraltar'),
	('GRD', 'Granada'),
	('GRC', 'Grécia'),
	('GRL', 'Gronelândia'),
	('GLP', 'Guadalupe'),
	('GUM', 'Guam'),
	('GTM', 'Guatemala'),
	('GIN', 'Guiné'),
	('GNB', 'Guiné-Bissau'),
	('GNQ', 'Guiné Equatorial'),
	('GUY', 'Guiana'),
	('GUF', 'Guiana Francesa'),
	('HTI', 'Haiti'),
	('HND', 'Honduras'),
	('HKG', 'Hong Kong'),
	('HUN', 'Hungria'),
	('YEM', 'Iémen'),
	('IND', 'Índia'),
	('IDN', 'Indonésia'),
	('ENG', 'Inglaterra'),
	('IRN', 'Irão'),
	('IRQ', 'Iraque'),
	('IRL', 'Irlanda'),
	('NIR', 'Irlanda do Norte'),
	('IMN', 'Ilha de Man'),
	('ISL', 'Islândia'),
	('ISR', 'Israel'),
	('ITA', 'Itália'),
	('JAM', 'Jamaica'),
	('JPN', 'Japão'),
	('JOR', 'Jordânia'),
	('KIR', 'Kiribati'),
	('KWT', 'Kuwait'),
	('LAO', 'Laos'),
	('LVA', 'Letônia'),
	('LSO', 'Lesoto'),
	('LBN', 'Líbano'),
	('LBR', 'Libéria'),
	('LBY', 'Líbia'),
	('LIE', 'Liechtenstein'),
	('LTU', 'Lituânia'),
	('LUX', 'Luxemburgo'),
	('MAC', 'Macau'),
	('MKD', 'Macedónia'),
	('MDG', 'Madagáscar'),
	('MYS', 'Malásia'),
	('MWI', 'Malaui'),
	('MDV', 'Maldivas'),
	('MLI', 'Mali'),
	('MLT', 'Malta'),
	('FLK', 'Ilhas Malvinas'),
	('MHL', 'Ilhas Marshall'),
	('MNP', 'Marianas Setentrionais'),
	('MAR', 'Marrocos'),
	('MTQ', 'Martinica'),
	('MRT', 'Mauritânia'),
	('MUS', 'Maurícia'),
	('MYT', 'Mayotte'),
	('MEX', 'México'),
	('MMR', 'Mianmar'),
	('MDA', 'Moldávia'),
	('MCO', 'Mónaco'),
	('MNG', 'Mongólia'),
	('MNE', 'Montenegro'),
	('MSR', 'Montserrat'),
	('MOZ', 'Moçambique'),
	('NAM', 'Namíbia'),
	('NRU', 'Nauru'),
	('NPL', 'Nepal'),
	('NCL', 'Nova Caledônia'),
	('NZL', 'Nova Zelândia'),
	('NIC', 'Nicarágua'),
	('NER', 'Níger'),
	('NGA', 'Nigéria'),
	('NIU', 'Niue'),
	('NFK', 'Ilha Norfolk'),
	('NOR', 'Noruega'),
	('OMN', 'Omã'),
	('WAL', 'País de Gales'),
	('NLD', 'Países Baixos'),
	('PLW', 'Palau'),
	('PSE', 'Palestina'),
	('PAN', 'Panamá'),
	('PNG', 'Papua-Nova Guiné'),
	('PAK', 'Paquistão'),
	('PRY', 'Paraguai'),
	('PER', 'Peru'),
	('PYF', 'Polinésia Francesa'),
	('POL', 'Polónia'),
	('PRT', 'Portugal'),
	('PRI', 'Porto Rico'),
	('QAT', 'Qatar'),
	('KEN', 'Quênia'),
	('KGZ', 'Quirguistão'),
	('GBR', 'Reino Unido'),
	('VGB', 'Ilhas Virgens Britânicas'),
	('CAF', 'República Centro-Africana'),
	('CZE', 'República Checa'),
	('COD', 'República Democrática do Congo'),
	('DOM', 'República Dominicana'),
	('TWN', 'Taiwan'),
	('ROU', 'Romênia'),
	('RUS', 'Rússia'),
	('RWA', 'Ruanda'),
	('ESH', 'Saara Ocidental'),
	('SLB', 'Ilhas Salomão'),
	('WSM', 'Samoa'),
	('ASM', 'Samoa Americana'),
	('BLM', 'Saint-Barthélemy'),
	('LCA', 'Santa Lúcia'),
	('MAF', 'Saint Martin'),
	('KNA', 'São Cristóvão e Névis'),
	('SPM', 'São Pedro e Miquelão'),
	('VCT', 'São Vicente e Granadinas'),
	('SMR', 'São Marinho'),
	('STP', 'São Tomé e Príncipe'),
	('SEN', 'Senegal'),
	('SLE', 'Serra Leoa'),
	('SRB', 'Sérvia'),
	('SYC', 'Seychelles'),
	('SGP', 'Singapura'),
	('SYR', 'Síria'),
	('SOM', 'Somália'),
	('LKA', 'Sri Lanka'),
	('SDN', 'Sudão'),
	('SWE', 'Suécia'),
	('SWZ', 'Suazilândia'),
	('CHE', 'Suíça'),
	('SUR', 'Suriname'),
	('TJK', 'Tadjiquistão'),
	('THA', 'Tailândia'),
	('TZA', 'Tanzânia'),
	('TLS', 'Timor-Leste'),
	('TGO', 'Togo'),
	('TKL', 'Toquelau'),
	('TON', 'Tonga'),
	('TTO', 'Trinidad e Tobago'),
	('TUN', 'Tunísia'),
	('TKM', 'Turcomenistão'),
	('TUR', 'Turquia'),
	('TCA', 'Turcas e Caicos'),
	('TUV', 'Tuvalu'),
	('UKR', 'Ucrânia'),
	('UGA', 'Uganda'),
	('VIR', 'Ilhas Virgens Americanas'),
	('URY', 'Uruguai'),
	('UZB', 'Uzbequistão'),
	('VUT', 'Vanuatu'),
	('VAT', 'Vaticano'),
	('VEN', 'Venezuela'),
	('VNM', 'Vietname'),
	('WLF', 'Wallis e Futuna'),
	('ZMB', 'Zâmbia'),
	('ZWE', 'Zimbábue')